# T-test

In [2]:
import scipy.stats
import numpy as np
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]
print('mean of M:'+str(np.mean(dat_M)))
print('mean of F:'+str(np.mean(dat_F)))
scipy.stats.ttest_ind(dat_M, dat_F, equal_var=False)

mean of M:100.0
mean of F:108.0


Ttest_indResult(statistic=-2.670573872669349, pvalue=0.01108318824471652)

In [10]:
import pandas as pd
import scipy.stats as stats
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
result_ct = pd.crosstab(diamonds.cut,diamonds.color)
stats.chi2_contingency(observed=result_ct)

(310.31790052115434,
 1.394512091985105e-51,
 24,
 array([[ 202.22005933,  292.42065258,  284.80941787,  337.04338154,
          247.85761958,  161.83574342,   83.8131257 ],
        [ 616.2059696 ,  891.06566555,  867.87267334, 1027.04026696,
          755.27296997,  493.1466815 ,  255.39577308],
        [2706.85993697, 3914.25930664, 3812.37749351, 4511.56640712,
         3317.7512792 , 2166.28702262, 1121.89855395],
        [1732.18437152, 2504.82808676, 2439.63147942, 2887.05917686,
         2123.1083426 , 1386.25884316,  717.92969967],
        [1517.52966259, 2194.42628847, 2137.30893585, 2529.29076752,
         1860.00978865, 1214.47170931,  628.96284761]]))

In [14]:
import pandas as pd
from scipy.stats import fisher_exact
df = pd.DataFrame({'drug A':[80, 50], 'drug B':[48, 70]},\
                  index=pd.Index(['no disease', 'disease']))
oddsr, p = fisher_exact(table=df.to_numpy(), alternative='two-sided')
oddsr, p

(2.3333333333333335, 0.001425903669576289)

In [15]:
import numpy as np
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]
print('mean of M:'+str(np.mean(dat_M)))
print('mean of F:'+str(np.mean(dat_F)))
np.corrcoef(dat_M,dat_F)

mean of M:100.0
mean of F:108.0


array([[1.        , 0.20059427],
       [0.20059427, 1.        ]])

In [1]:
from scipy.stats import ranksums
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]
ranksums(dat_M,dat_F)

RanksumsResult(statistic=-2.677958814962274, pvalue=0.007407232568616353)

In [2]:
from scipy.stats import kruskal
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]
dat_N = [12, 10, 10, 11, 10, 10, 10, 13, 9, 19, 10, 13, 11, 9, 18, 6, 11, 11, 10, 10]
kruskal(dat_M,dat_F,dat_N)

KruskalResult(statistic=42.72032465902437, pvalue=5.289314220067243e-10)

In [8]:
X = np.array(X)

In [ ]:
X.reshape

In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression
X= np.array([117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]).reshape(-1,1)
y = np.array([121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100])
line_fitter = LinearRegression()
line_fitter.fit(X, y)
line_fitter.coef_ , line_fitter.intercept_

(array([0.19883721]), 88.11627906976744)

In [13]:
import numpy as np
from sklearn.linear_model import LogisticRegression
X= np.array([117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]).reshape(-1,1)
y = np.array([1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0])
line_fitter = LogisticRegression()
line_fitter.fit(X, y)
line_fitter.coef_ , line_fitter.intercept_

(array([[0.04337012]]), array([-3.91290753]))

In [25]:
import urllib
import numpy as np
import pandas as pd
from statsmodels.stats.anova import anova_lm
from statsmodels.formula.api import ols
import scipy.stats as stats
url = 'https://raw.githubusercontent.com/thomas-haslwanter/statsintro_python/master/ipynb/Data/data_altman/altman_910.txt'
data = np.genfromtxt(urllib.request.urlopen(url), delimiter=',')
df = pd.DataFrame(data, columns=['value', 'treatment'])    
model = ols('value ~ C(treatment)', df).fit()
print(anova_lm(model))

                df        sum_sq      mean_sq         F    PR(>F)
C(treatment)   2.0  15515.766414  7757.883207  3.711336  0.043589
Residual      19.0  39716.097222  2090.320906       NaN       NaN
